# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-11 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('abreviatura', models.CharField(max_length=10)),
                ('nivel_profesional', models.IntegerField()),
            ],
            options={
                'db_table': 'ciclos',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_curso', models.IntegerField()),
                ('nombre_curso', models.CharField(max_length=20)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Ciclo')),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='EspecialidadProfesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(choices=[('PS', 'Prof. Secundaria'), ('PT', 'Prof. Tecnico')], max_length=30)),
            ],
            options={
                'db_table': 'especialidesprofesorado',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=15)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Curso')),
            ],
            options={
                'db_table': 'grupos',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('codigo_junta', models.IntegerField()),
                ('horas_anuales', models.IntegerField()),
                ('horas_semanales', models.IntegerField()),
                ('especialidad', models.CharField(max_length=10)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Curso')),
            ],
            options={
                'ordering': ['nombre', 'curso'],
                'db_table': 'modulos',
                'verbose_name_plural': 'Modulos',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('horas_minimas', models.IntegerField()),
                ('num_posicion', models.IntegerField()),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.EspecialidadProfesor')),
            ],
            options={
                'db_table': 'profesores',
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
    ]
