# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-11 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulosAsignados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Modulo')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Profesor')),
                ('reparto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Reparto')),
            ],
        ),
        migrations.CreateModel(
            name='ModulosNoAsignados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Modulo')),
                ('reparto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.Reparto')),
            ],
        ),
    ]
